### ISSUE TITLE
Remove Travis CI

### ISSUE THREAD

**Issue by liziwl** [SUSTC/sustc.github.io#7]
@ProfFan pls remove Travis CI

**Comment by liziwl** [comment]
![image](https://user-images.githubusercontent.com/23000702/64950266-868f7080-d8ad-11e9-96e9-df6087949cf6.png)
There may be other places about the configuration of Travis ci. Pls remove them all.

**Comment by liziwl** [comment]
Then, I will config GitHub action. In order not to configure multiple ci.

**Comment by ProfFan** [comment]
I prefer u add GHCI first?

**Comment by liziwl** [comment]
OK, I try to deploy first.

**Comment by liziwl** [comment]
Done, now can remove Travis CI.
